class Question {
  final String questionText;
  final List<String> answers;
  final int correctAnswerIndex;

  const Question({
    required this.questionText,
    required this.answers,
    required this.correctAnswerIndex,
  });
}

enum QuizCategory {
  programming,
  islamic
}

final Map<QuizCategory, List<Question>> questionBank = {
  QuizCategory.programming: [
    const Question(questionText: 'Apa kepanjangan HTML?', answers: ['Hyper Tool Markup Language', 'Hyper Text Markup Language', 'Home Tool Markup Language', 'Hyperlinks Text Mark Language'], correctAnswerIndex: 1),
    const Question(questionText: 'Bahasa pemrograman apa yang digunakan untuk membuat aplikasi Flutter?', answers: ['Java', 'Kotlin', 'Dart', 'Swift'], correctAnswerIndex: 2),
    const Question(questionText: 'Apa kepanjangan CSS?', answers: ['Creative Style Sheets', 'Computer Style Sheets', 'Cascading Style Sheets', 'Colorful Style Sheets'], correctAnswerIndex: 2),
    const Question(questionText: 'Manakah yang merupakan sistem operasi?', answers: ['Microsoft Word', 'Google Chrome', 'Linux', 'Visual Studio Code'], correctAnswerIndex: 2),
    const Question(questionText: 'Apa fungsi utama dari RAM pada komputer?', answers: ['Menyimpan data secara permanen', 'Memproses grafis', 'Menyimpan data sementara saat komputer menyala', 'Menghubungkan ke internet'], correctAnswerIndex: 2),
    const Question(questionText: 'Apa kepanjangan dari CPU?', answers: ['Central Process Unit', 'Computer Personal Unit', 'Central Processing Unit', 'Central Program Utility'], correctAnswerIndex: 2),
    const Question(questionText: 'Bahasa pemrograman apa yang paling populer untuk pengembangan web frontend?', answers: ['Python', 'JavaScript', 'C++', 'Ruby'], correctAnswerIndex: 1),
    const Question(questionText: 'Apa itu Git?', answers: ['Bahasa pemrograman', 'Sistem manajemen database', 'Sistem kontrol versi', 'Framework web'], correctAnswerIndex: 2),
    const Question(questionText: 'Manakah yang bukan bahasa pemrograman?', answers: ['Python', 'Photoshop', 'Java', 'Go'], correctAnswerIndex: 1),
    const Question(questionText: 'Apa fungsi dari DNS?', answers: ['Mengenkripsi data', 'Menerjemahkan nama domain ke alamat IP', 'Menyimpan file', 'Mengirim email'], correctAnswerIndex: 1),
    const Question(questionText: 'Apa kepanjangan dari URL?', answers: ['Uniform Resource Locator', 'Universal Reference Link', 'Uniform Reference Locator', 'Universal Resource Locator'], correctAnswerIndex: 0),
    const Question(questionText: 'Berapa bit dalam 1 byte?', answers: ['4 bit', '8 bit', '16 bit', '32 bit'], correctAnswerIndex: 1),
    const Question(questionText: 'Apa itu firewall?', answers: ['Perangkat keras untuk mencetak', 'Sistem keamanan jaringan', 'Aplikasi pengolah kata', 'Jenis kabel jaringan'], correctAnswerIndex: 1),
    const Question(questionText: 'Framework manakah yang dibuat oleh Google untuk mobile development?', answers: ['React Native', 'Xamarin', 'Flutter', 'Ionic'], correctAnswerIndex: 2),
    const Question(questionText: 'Apa kepanjangan dari API?', answers: ['Application Programming Interface', 'Applied Program Integration', 'Application Process Interface', 'Automated Programming Interface'], correctAnswerIndex: 0),
    const Question(questionText: 'Apa itu database relasional?', answers: ['Database yang menyimpan data dalam bentuk gambar', 'Database yang menyimpan data dalam bentuk tabel dengan relasi', 'Database tanpa struktur', 'Database yang hanya menyimpan teks'], correctAnswerIndex: 1),
    const Question(questionText: 'Manakah yang merupakan bahasa markup?', answers: ['Python', 'Java', 'HTML', 'C#'], correctAnswerIndex: 2),
    const Question(questionText: 'Apa itu cloud computing?', answers: ['Komputasi menggunakan awan', 'Penyediaan layanan komputasi melalui internet', 'Penyimpanan data di harddisk', 'Jaringan komputer lokal'], correctAnswerIndex: 1),
    const Question(questionText: 'Apa kepanjangan dari SSD?', answers: ['Solid State Drive', 'Super Speed Disk', 'System Storage Device', 'Solid System Drive'], correctAnswerIndex: 0),
    const Question(questionText: 'Siapa pendiri Microsoft?', answers: ['Steve Jobs', 'Mark Zuckerberg', 'Bill Gates', 'Elon Musk'], correctAnswerIndex: 2),
    const Question(questionText: 'Apa itu algoritma?', answers: ['Jenis komputer', 'Langkah-langkah sistematis untuk menyelesaikan masalah', 'Bahasa pemrograman', 'Perangkat keras komputer'], correctAnswerIndex: 1),
    const Question(questionText: 'Manakah dari berikut ini yang merupakan tipe data untuk bilangan bulat?', answers: ['Float', 'String', 'Integer', 'Boolean'], correctAnswerIndex: 2),
    const Question(questionText: 'Apa fungsi tag <a> pada HTML?', answers: ['Membuat tabel', 'Membuat paragraf', 'Membuat hyperlink', 'Membuat gambar'], correctAnswerIndex: 2),
    const Question(questionText: 'Dalam pemrograman, apa fungsi dari array?', answers: ['Menyimpan satu nilai', 'Menyimpan banyak nilai dalam satu variabel', 'Menjalankan perulangan', 'Mencetak output ke layar'], correctAnswerIndex: 1),
    const Question(questionText: 'Apa itu loop (perulangan)?', answers: ['Kondisi percabangan', 'Struktur data', 'Blok kode yang dijalankan berulang kali', 'Tipe variabel'], correctAnswerIndex: 2),
    const Question(questionText: 'Manakah yang merupakan perintah untuk mencetak output di Python?', answers: ['echo()', 'print()', 'console.log()', 'printf()'], correctAnswerIndex: 1),
    const Question(questionText: 'Apa yang dimaksud dengan variabel?', answers: ['Perintah untuk berhenti', 'Tempat menyimpan data di memori', 'Sebuah fungsi bawaan', 'Jenis error dalam kode'], correctAnswerIndex: 1),
    const Question(questionText: 'Sistem bilangan yang hanya menggunakan angka 0 dan 1 disebut?', answers: ['Desimal', 'Oktal', 'Heksadesimal', 'Biner'], correctAnswerIndex: 3),
    const Question(questionText: 'Apa itu debugging?', answers: ['Proses menulis kode baru', 'Proses mencari dan memperbaiki error/bug', 'Proses menghapus komentar', 'Proses menjalankan aplikasi'], correctAnswerIndex: 1),
    const Question(questionText: 'Tag HTML mana yang digunakan untuk teks paling tebal/besar?', answers: ['<h1>', '<head>', '<h6>', '<title>'], correctAnswerIndex: 0),
    const Question(questionText: 'Apa itu HTTP?', answers: ['Bahasa pemrograman', 'Protokol transfer data di web', 'Sistem operasi', 'Jenis database'], correctAnswerIndex: 1),
    const Question(questionText: 'Siapa pencipta bahasa pemrograman Linux?', answers: ['Bill Gates', 'Steve Jobs', 'Linus Torvalds', 'Dennis Ritchie'], correctAnswerIndex: 2),
    const Question(questionText: 'Apa ekstensi file untuk kode Java?', answers: ['.js', '.java', '.jv', '.jav'], correctAnswerIndex: 1),
    const Question(questionText: 'Apa yang dilakukan perintah "git commit"?', answers: ['Menghapus file', 'Menyimpan perubahan ke repositori lokal', 'Mengirim perubahan ke server', 'Menggabungkan cabang'], correctAnswerIndex: 1),
    const Question(questionText: 'Manakah yang merupakan contoh DBMS (Database Management System)?', answers: ['Microsoft Excel', 'MySQL', 'Node.js', 'React'], correctAnswerIndex: 1),
    const Question(questionText: 'Apa kepanjangan dari SQL?', answers: ['Structured Query Language', 'Simple Question Language', 'Standard Query Logic', 'System Quality Level'], correctAnswerIndex: 0),
    const Question(questionText: 'Fungsi mana yang digunakan untuk panjang string di JavaScript?', answers: ['size()', 'length()', 'count', 'length'], correctAnswerIndex: 3),
    const Question(questionText: 'Simbol apa yang digunakan untuk komentar satu baris di C++ atau Java?', answers: ['//', '#', '<!--', '/*'], correctAnswerIndex: 0),
    const Question(questionText: 'Apa itu IDE?', answers: ['Internet Development Environment', 'Integrated Development Environment', 'Internal Data Execution', 'Interactive Design Engine'], correctAnswerIndex: 1),
    const Question(questionText: 'Manakah yang digunakan untuk menata letak halaman web?', answers: ['HTML', 'JavaScript', 'CSS', 'PHP'], correctAnswerIndex: 2),
    const Question(questionText: 'Apa itu framework?', answers: ['Alat pembersih virus', 'Kerangka kerja perangkat lunak', 'Sistem operasi berbasis teks', 'Aplikasi pengolah gambar'], correctAnswerIndex: 1),
    const Question(questionText: 'Mana dari ini yang berjalan di sisi server (backend)?', answers: ['CSS', 'HTML', 'Node.js', 'React'], correctAnswerIndex: 2),
    const Question(questionText: 'Apa arti nilai Boolean?', answers: ['Angka desimal', 'Teks dan huruf', 'True atau False', 'Array kosong'], correctAnswerIndex: 2),
    const Question(questionText: 'Bahasa apa yang digunakan untuk membuat query database?', answers: ['Python', 'SQL', 'HTML', 'Java'], correctAnswerIndex: 1),
    const Question(questionText: 'Perusahaan mana yang mengembangkan React?', answers: ['Google', 'Microsoft', 'Apple', 'Meta (Facebook)'], correctAnswerIndex: 3),
    const Question(questionText: 'Apa itu OOP?', answers: ['Object-Oriented Programming', 'Online Output Process', 'Overriding Output Parameters', 'Operator Object Protocol'], correctAnswerIndex: 0),
    const Question(questionText: 'Manakah dari ini yang merupakan editor teks untuk coding?', answers: ['Adobe Photoshop', 'VS Code', 'Microsoft Word', 'Google Chrome'], correctAnswerIndex: 1),
    const Question(questionText: 'Siapa yang menciptakan bahasa Python?', answers: ['James Gosling', 'Guido van Rossum', 'Bjarne Stroustrup', 'Dennis Ritchie'], correctAnswerIndex: 1),
    const Question(questionText: 'Apa tujuan utama dari bahasa CSS?', answers: ['Membuat animasi 3D', 'Styling dan tata letak HTML', 'Menulis query database', 'Menghubungkan server'], correctAnswerIndex: 1),
    const Question(questionText: 'Manakah yang bukan bagian dari konsep OOP?', answers: ['Inheritance', 'Polymorphism', 'Encapsulation', 'Compilation'], correctAnswerIndex: 3),
  ],
  QuizCategory.islamic: [
    const Question(questionText: 'Rukun Islam yang pertama adalah?', answers: ['Shalat', 'Zakat', 'Syahadat', 'Puasa'], correctAnswerIndex: 2),
    const Question(questionText: 'Ada berapa jumlah Rukun Iman?', answers: ['4', '5', '6', '7'], correctAnswerIndex: 2),
    const Question(questionText: 'Kitab suci Al-Qur\'an diturunkan kepada Nabi?', answers: ['Nabi Musa AS', 'Nabi Isa AS', 'Nabi Daud AS', 'Nabi Muhammad SAW'], correctAnswerIndex: 3),
    const Question(questionText: 'Malaikat yang bertugas menyampaikan wahyu adalah?', answers: ['Mikail', 'Jibril', 'Israfil', 'Izrail'], correctAnswerIndex: 1),
    const Question(questionText: 'Berapa jumlah nabi dan rasul yang wajib diimani?', answers: ['10', '20', '25', '99'], correctAnswerIndex: 2),
    const Question(questionText: 'Bulan suci tempat umat Islam diwajibkan berpuasa adalah?', answers: ['Muharram', 'Rajab', 'Ramadhan', 'Syawal'], correctAnswerIndex: 2),
    const Question(questionText: 'Ibadah Haji wajib dilaksanakan di kota?', answers: ['Madinah', 'Mekkah', 'Yerusalem', 'Kairo'], correctAnswerIndex: 1),
    const Question(questionText: 'Apa arti dari Asmaul Husna?', answers: ['Sifat-sifat buruk', 'Nama-nama Allah yang baik', 'Nama-nama Malaikat', 'Nama-nama Nabi'], correctAnswerIndex: 1),
    const Question(questionText: 'Berapa jumlah Asmaul Husna?', answers: ['99', '100', '25', '114'], correctAnswerIndex: 0),
    const Question(questionText: 'Hari kiamat juga disebut dengan Yaumul?', answers: ['Mizan', 'Hisab', 'Qiyamah', 'Jaza\''], correctAnswerIndex: 2),
    const Question(questionText: 'Surah pertama dalam Al-Qur\'an adalah?', answers: ['Al-Baqarah', 'Yasin', 'Al-Ikhlas', 'Al-Fatihah'], correctAnswerIndex: 3),
    const Question(questionText: 'Shalat wajib yang dikerjakan pada sore hari adalah?', answers: ['Dhuhur', 'Ashar', 'Maghrib', 'Isya'], correctAnswerIndex: 1),
    const Question(questionText: 'Zakat yang wajib dikeluarkan setiap bulan Ramadhan sebelum Idul Fitri disebut?', answers: ['Zakat Mal', 'Zakat Fitrah', 'Infaq', 'Sedekah'], correctAnswerIndex: 1),
    const Question(questionText: 'Istri pertama Nabi Muhammad SAW adalah?', answers: ['Aisyah', 'Khadijah', 'Fatimah', 'Hafsah'], correctAnswerIndex: 1),
    const Question(questionText: 'Tempat turunnya wahyu pertama kepada Nabi Muhammad SAW adalah?', answers: ['Gua Hira', 'Gua Tsur', 'Bukit Shafa', 'Masjidil Haram'], correctAnswerIndex: 0),
    const Question(questionText: 'Berapa jumlah rakaat dalam shalat Maghrib?', answers: ['2', '3', '4', '5'], correctAnswerIndex: 1),
    const Question(questionText: 'Apa nama malam kemuliaan di bulan Ramadhan yang lebih baik dari seribu bulan?', answers: ['Lailatul Qadar', 'Nuzulul Quran', 'Isra Mi\'raj', 'Maulid Nabi'], correctAnswerIndex: 0),
    const Question(questionText: 'Sahabat Nabi yang menjadi Khalifah pertama adalah?', answers: ['Umar bin Khattab', 'Usman bin Affan', 'Abu Bakar Ash-Shiddiq', 'Ali bin Abi Thalib'], correctAnswerIndex: 2),
    const Question(questionText: 'Peristiwa perjalanan malam Nabi Muhammad SAW dari Masjidil Haram ke Masjidil Aqsa disebut?', answers: ['Hijrah', 'Isra\'', 'Mi\'raj', 'Fathu Makkah'], correctAnswerIndex: 1),
    const Question(questionText: 'Nabi yang ditelan oleh ikan paus adalah?', answers: ['Nabi Ibrahim', 'Nabi Nuh', 'Nabi Yunus', 'Nabi Ayub'], correctAnswerIndex: 2),
    const Question(questionText: 'Nabi yang memiliki mukjizat tongkat berubah menjadi ular adalah?', answers: ['Nabi Sulaiman', 'Nabi Musa', 'Nabi Isa', 'Nabi Yusuf'], correctAnswerIndex: 1),
    const Question(questionText: 'Siapakah malaikat yang bertugas meniup sangkakala?', answers: ['Jibril', 'Mikail', 'Israfil', 'Izrail'], correctAnswerIndex: 2),
    const Question(questionText: 'Malaikat yang bertugas mencatat amal baik adalah?', answers: ['Atid', 'Rakib', 'Ridwan', 'Malik'], correctAnswerIndex: 1),
    const Question(questionText: 'Surah yang menceritakan tentang keesaan Allah SWT adalah?', answers: ['Al-Falaq', 'An-Nas', 'Al-Ikhlas', 'Al-Kafirun'], correctAnswerIndex: 2),
    const Question(questionText: 'Apa arti kata "Islam"?', answers: ['Kepercayaan', 'Kepatuhan/Keselamatan', 'Agama', 'Perdamaian dunia'], correctAnswerIndex: 1),
    const Question(questionText: 'Siapa nama ibu kandung Nabi Muhammad SAW?', answers: ['Siti Hajar', 'Siti Maryam', 'Aminah', 'Halimah'], correctAnswerIndex: 2),
    const Question(questionText: 'Siapa nama kakek Nabi Muhammad SAW yang mengasuhnya?', answers: ['Abu Thalib', 'Abdul Muthalib', 'Abdullah', 'Hamzah'], correctAnswerIndex: 1),
    const Question(questionText: 'Perang pertama dalam sejarah Islam adalah?', answers: ['Perang Uhud', 'Perang Khandaq', 'Perang Badar', 'Perang Tabuk'], correctAnswerIndex: 2),
    const Question(questionText: 'Gelar "Al-Amin" yang diberikan kepada Nabi Muhammad SAW berarti?', answers: ['Yang cerdas', 'Yang dapat dipercaya', 'Yang kuat', 'Yang penyabar'], correctAnswerIndex: 1),
    const Question(questionText: 'Berapa tahun lamanya Al-Qur\'an diturunkan?', answers: ['20 tahun', '21 tahun', '22 tahun 2 bulan 22 hari', '25 tahun'], correctAnswerIndex: 2),
    const Question(questionText: 'Surah terpanjang dalam Al-Qur\'an adalah?', answers: ['Ali Imran', 'An-Nisa', 'Al-Baqarah', 'Al-Maidah'], correctAnswerIndex: 2),
    const Question(questionText: 'Nabi yang membangun Ka\'bah bersama putranya adalah?', answers: ['Nabi Nuh & Sam', 'Nabi Ibrahim & Ismail', 'Nabi Yaqub & Yusuf', 'Nabi Daud & Sulaiman'], correctAnswerIndex: 1),
    const Question(questionText: 'Air suci yang muncul di dekat Ka\'bah dari zaman Siti Hajar disebut?', answers: ['Air Kautsar', 'Air Zamzam', 'Air Salsabila', 'Air Tasnim'], correctAnswerIndex: 1),
    const Question(questionText: 'Arah kiblat umat Islam saat shalat adalah menuju?', answers: ['Masjidil Aqsa', 'Masjid Nabawi', 'Ka\'bah', 'Bukit Tursina'], correctAnswerIndex: 2),
    const Question(questionText: 'Puasa sunnah yang dilakukan pada hari Senin dan Kamis disebut?', answers: ['Puasa Daud', 'Puasa Arafah', 'Puasa Senin-Kamis', 'Puasa Asyura'], correctAnswerIndex: 2),
    const Question(questionText: 'Berapa persen besaran Zakat Mal (harta) yang harus dikeluarkan?', answers: ['1.5%', '2.5%', '5%', '10%'], correctAnswerIndex: 1),
    const Question(questionText: 'Shalat sunnah yang mengiringi shalat fardhu disebut shalat?', answers: ['Tahajjud', 'Dhuha', 'Rawatib', 'Witir'], correctAnswerIndex: 2),
    const Question(questionText: 'Shalat yang dikerjakan pada malam hari setelah tidur disebut shalat?', answers: ['Tarawih', 'Tahajjud', 'Hajat', 'Istikharah'], correctAnswerIndex: 1),
    const Question(questionText: 'Siapa malaikat yang bertugas menjaga pintu surga?', answers: ['Malik', 'Ridwan', 'Munkar', 'Nakir'], correctAnswerIndex: 1),
    const Question(questionText: 'Nabi yang diberi mukjizat bisa berbicara dengan hewan adalah?', answers: ['Nabi Daud', 'Nabi Sulaiman', 'Nabi Musa', 'Nabi Yunus'], correctAnswerIndex: 1),
    const Question(questionText: 'Berapa jumlah juz dalam Al-Qur\'an?', answers: ['114', '99', '30', '6666'], correctAnswerIndex: 2),
    const Question(questionText: 'Hewan apa yang dikisahkan menemani pemuda Ashabul Kahfi tertidur?', answers: ['Kucing', 'Kuda', 'Unta', 'Anjing'], correctAnswerIndex: 3),
    const Question(questionText: 'Siapa tokoh kafir Quraisy yang menentang dakwah Nabi dan disebut namanya dalam Al-Qur\'an?', answers: ['Firaun', 'Abu Jahal', 'Abu Lahab', 'Namrud'], correctAnswerIndex: 2),
    const Question(questionText: 'Bulan Islam yang pertama dalam kalender Hijriah adalah?', answers: ['Ramadhan', 'Muharram', 'Safar', 'Dzulhijjah'], correctAnswerIndex: 1),
    const Question(questionText: 'Apa hukumnya melaksanakan shalat lima waktu bagi muslim baligh?', answers: ['Sunnah', 'Mubah', 'Wajib', 'Makruh'], correctAnswerIndex: 2),
    const Question(questionText: 'Orang yang mengumandangkan adzan disebut?', answers: ['Imam', 'Khatib', 'Makmum', 'Muadzin'], correctAnswerIndex: 3),
    const Question(questionText: 'Bersuci dengan debu ketika tidak ada air disebut?', answers: ['Wudhu', 'Mandi wajib', 'Tayamum', 'Istinja'], correctAnswerIndex: 2),
    const Question(questionText: 'Pakaian putih tanpa jahitan yang dipakai saat ibadah Haji disebut?', answers: ['Sorban', 'Ihram', 'Jubah', 'Gamis'], correctAnswerIndex: 1),
    const Question(questionText: 'Membaca Al-Qur\'an dengan tajwid yang benar hukumnya?', answers: ['Fardhu Kifayah', 'Sunnah', 'Mubah', 'Fardhu Ain'], correctAnswerIndex: 3),
    const Question(questionText: 'Kata "Al-Qur\'an" secara harfiah berarti?', answers: ['Bacaan', 'Petunjuk', 'Cahaya', 'Pembeda'], correctAnswerIndex: 0),
  ],
};
